#!/bin/bash

#docker inspect --format "{{json .State.Health }}" $1 | jq

CONTAINERIDS=$(docker ps -q) || exit 1

hostnames=()

echo ContainerIDs: $CONTAINERIDS

for container in $CONTAINERIDS; do
  echo Container: $container
  hostname=$(docker exec -it $container "hostname" 2>/dev/null)
  #echo hostname: $hostname
  hostnames+=( $hostname )
  #docker exec $container "which dig && dig $hostname || nslookup $hostname" 
done
echo "*****"

echo Hostnames: $hostnames

for container in $CONTAINERIDS; do
  echo container: $container
  #for hostname in ${hostnames[@]}; do
  #  echo testing: $hostname
  #  docker exec $container "dig +timeout=1 $hostname" 2>&1 >/dev/null && echo --OK-- || echo --ERROR--
  #done
echo "*****"
done
