---
  - name: "Setup docker host - ubuntu 18.04 LTS"
    hosts: localhost
    connection: local
    vars:
      pkgs:
      - wireguard
      - docker.io
        #- docker-ce
        #- docker-ce-cli
      - docker-compose
        #- containerd.io
      - git

    tasks:
    # Install packages
    - apt: name={{ pkgs }} state=latest
      become: yes

    # Setup swapspace
    - set_fact: swap_space="1G"
    - set_fact: swap_file="/{{ swap_space }}.swap"
    - stat: path="{{ swap_file }}"
      register: swap_file_check
    - command: fallocate -l {{ swap_space }} {{ swap_file }}
      become: yes
      when: not swap_file_check.stat.exists
    - file:
        path: "{{ swap_file }}"
        mode: 0600
      become: yes
    - command: mkswap {{ swap_file }}
      become: yes
      when: not swap_file_check.stat.exists
    - lineinfile:
        dest: /etc/fstab
        regexp: "{{ swap_file }}"
        line: "{{ swap_file }} none swap sw 0 0"
      become: yes
    - command: swapon -a
      become: yes
    - sysctl:
        name: vm.swappiness
        value: "1"
      become: yes


    # Install wireguard
    - modprobe: name=wireguard
      become: yes
    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
      become: yes
    - sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        sysctl_set: yes
      become: yes
    - sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
        sysctl_set: yes
      become: yes
    - sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: '1'
        sysctl_set: yes
      become: yes



    # sshd setup
    - command: sed -i 's/^[#]*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      become: yes
    - service: name=sshd state=reloaded
      become: yes


    # Fix DNS resolver
    - systemd: name=systemd-resolved state=stopped
      become: yes
    - service: name=systemd-resolved state=stopped
      become: yes
    - command: |
        echo "nameserver 172.26.0.2
        nameserver 1.1.1.1
        search eu-west-2.compute.internal"
      register: dnsoutput
    - copy: content={{ dnsoutput.stdout }} dest=/etc/resolv.conf
      become: yes


    # Install docker
    - group: name=docker
      become: yes
    - user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      become: yes
    - command: |
        echo "{
          "dns": ["1.1.1.2", "1.0.0.2"],
          "dns-opts":["use-vc"],
          "dns-search": ["vpn"]
        }"
      register: dockeroutput
    - copy: content={{ dockeroutput.stdout }} dest=/etc/docker/daemon.json
    - service: name=docker state=reloaded
      become: yes

    # Setup timezone
    - timezone: name=Europe/London
      become: yes

    # Setup Git
    - command: git config credential.helper store
    - command: git config --global credential.helper 'cache --timeout 7200'
    - file:
        path: "{{ ansible_user_dir }}/deploy"
        state: directory
    - git:
        repo: https://github.com/dmccue/hotwire
        dest: "{{ ansible_user_dir }}/deploy/hotwire"

    # Write diag
    - uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: diag

    - copy: content={{ diag.content }} dest=/root/diag_externalip
      become: yes

    # - name: "just execute a ls -lrt command"
    #  shell: "ls -lrt"
    #  register: "output"

    #- debug: var=output.stdout_lines
