# This is a custom workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  build:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
    #- name: List installed software on github image
    #  run: apt list --installed
      
    - name: execute compose BUILD script via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          if [ -d ~/deploy/hotwire/ ]; then 
            cd ~/deploy/hotwire && docker-compose down
            cd ~
          fi
          sudo rm -rf ~/deploy/hotwire
          mkdir -p ~/deploy
          cd ~/deploy
          git clone https://github.com/dmccue/hotwire.git hotwire && cd hotwire
          echo Compose Down
          docker-compose down
          echo Compose Build
          docker-compose build --pull
          
          echo hostname: $(hostname -s)
          echo epoch: $(date +%s)
          echo pwd: $(pwd)
          

    - name: execute compose RUN script via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/deploy/hotwire
          echo Compose Up
          docker-compose up -d --force-recreate
          echo Compose ps
          docker-compose ps
          
          echo hostname: $(hostname -s)
          echo epoch: $(date +%s)
          echo pwd: $(pwd)

#    steps:
#    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2

#    # Runs a single command using the runners shell
#    - name: Run a one-line script
#      run: echo Hello, world!

    # Runs a set of commands using the runners shell
#    - name: Run a multi-line script
#      run: |
#        echo Add other actions to build,
#        echo test, and deploy your project.
