# This is a custom workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  build:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:


    - name: recreate deploy repo via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          if [ -d ~/deploy/hotwire/ ]; then
            cd ~/deploy/hotwire && docker-compose down && sudo rm -rf ~/deploy/hotwire
            cd ~
          fi
          mkdir -p ~/deploy && cd ~/deploy
          git clone https://github.com/dmccue/hotwire.git hotwire && cd hotwire || { echo Error encountered - exit code $?; exit 1; }
          echo Compose Down && \
          docker-compose down || { echo Error with compose down - exit code $?; exit 1; }

          echo hostname: $(hostname -s)
          echo epoch: $(date +%s)
          echo pwd: $(pwd)

    - name: Run ansible deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/deploy/hotwire &&
          ansible-playbook -v playbook.yml

          echo hostname: $(hostname -s)
          echo epoch: $(date +%s)
          echo pwd: $(pwd)


    - name: LINT test Dockerfiles via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/deploy/hotwire &&
          ./test-lint

          echo hostname: $(hostname -s)
          echo epoch: $(date +%s)
          echo pwd: $(pwd)


    - name: execute compose BUILD script via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/deploy/hotwire && \
          echo Compose Build && \
          docker-compose build --pull || { echo Error: build unsuccessful - exit code $?; docker info; exit 1; }

          echo hostname: $(hostname -s)
          echo epoch: $(date +%s)
          echo pwd: $(pwd)


    - name: execute compose RUN script via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/deploy/hotwire
          echo Compose Up && \
          export FQDN=$(curl http://169.254.169.254/latest/meta-data/public-hostname); \
          docker-compose up -d --force-recreate || { echo Error: compose up failed - exit code $?; docker-compose ps; exit 1; }
          echo Compose ps && \
          docker-compose ps

          echo hostname: $(hostname -s)
          echo epoch: $(date +%s)
          echo pwd: $(pwd)

#    steps:
#    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2

#    # Runs a single command using the runners shell
#    - name: Run a one-line script
#      run: echo Hello, world!

    # Runs a set of commands using the runners shell
#    - name: Run a multi-line script
#      run: |
#        echo Add other actions to build,
#        echo test, and deploy your project.
